# Generated by Django 5.2.12 on 2026-05-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_two_factor_enabled'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnss_employee_rate', models.DecimalField(decimal_places=2, default=7.0, max_digits=5)),
                ('cnss_employer_rate', models.DecimalField(decimal_places=2, default=14.0, max_digits=5)),
                ('ipres_employee_rate', models.DecimalField(decimal_places=2, default=5.6, max_digits=5)),
                ('ipres_employer_rate', models.DecimalField(decimal_places=2, default=8.4, max_digits=5)),
                ('irpp_estimated_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('irpp_threshold', models.DecimalField(decimal_places=2, default=250000.0, max_digits=12)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_config', to='accounts.company')),
            ],
        ),
    ]
