from django.utils.translation import gettext_lazy as _

COUNTRY_CHOICES = [
    ('Afghanistan', _('Afghanistan')),
    ('Afrique du Sud', _('Afrique du Sud')),
    ('Albanie', _('Albanie')),
    ('Algérie', _('Algérie')),
    ('Allemagne', _('Allemagne')),
    ('Andorre', _('Andorre')),
    ('Angola', _('Angola')),
    ('Antigua-et-Barbuda', _('Antigua-et-Barbuda')),
    ('Arabie saoudite', _('Arabie saoudite')),
    ('Argentine', _('Argentine')),
    ('Arménie', _('Arménie')),
    ('Australie', _('Australie')),
    ('Autriche', _('Autriche')),
    ('Azerbaïdjan', _('Azerbaïdjan')),
    ('Bahamas', _('Bahamas')),
    ('Bahreïn', _('Bahreïn')),
    ('Bangladesh', _('Bangladesh')),
    ('Barbade', _('Barbade')),
    ('Belgique', _('Belgique')),
    ('Belize', _('Belize')),
    ('Bénin', _('Bénin')),
    ('Bhoutan', _('Bhoutan')),
    ('Biélorussie', _('Biélorussie')),
    ('Birmanie', _('Birmanie')),
    ('Bolivie', _('Bolivie')),
    ('Bosnie-Herzégovine', _('Bosnie-Herzégovine')),
    ('Botswana', _('Botswana')),
    ('Brésil', _('Brésil')),
    ('Brunei', _('Brunei')),
    ('Bulgarie', _('Bulgarie')),
    ('Burkina Faso', _('Burkina Faso')),
    ('Burundi', _('Burundi')),
    ('Cambodge', _('Cambodge')),
    ('Cameroun', _('Cameroun')),
    ('Canada', _('Canada')),
    ('Cap-Vert', _('Cap-Vert')),
    ('Centrafrique', _('Centrafrique')),
    ('Chili', _('Chili')),
    ('Chine', _('Chine')),
    ('Chypre', _('Chypre')),
    ('Colombie', _('Colombie')),
    ('Comores', _('Comores')),
    ('Congo-Brazzaville', _('Congo-Brazzaville')),
    ('Congo-Kinshasa', _('Congo-Kinshasa')),
    ('Corée du Nord', _('Corée du Nord')),
    ('Corée du Sud', _('Corée du Sud')),
    ('Costa Rica', _('Costa Rica')),
    ('Côte d’Ivoire', _('Côte d’Ivoire')),
    ('Croatie', _('Croatie')),
    ('Cuba', _('Cuba')),
    ('Danemark', _('Danemark')),
    ('Djibouti', _('Djibouti')),
    ('Dominique', _('Dominique')),
    ('Égypte', _('Égypte')),
    ('Émirats arabes unis', _('Émirats arabes unis')),
    ('Équateur', _('Équateur')),
    ('Érythrée', _('Érythrée')),
    ('Espagne', _('Espagne')),
    ('Estonie', _('Estonie')),
    ('États-Unis', _('États-Unis')),
    ('Éthiopie', _('Éthiopie')),
    ('Fidji', _('Fidji')),
    ('Finlande', _('Finlande')),
    ('France', _('France')),
    ('Gabon', _('Gabon')),
    ('Gambie', _('Gambie')),
    ('Géorgie', _('Géorgie')),
    ('Ghana', _('Ghana')),
    ('Grèce', _('Grèce')),
    ('Grenade', _('Grenade')),
    ('Guatemala', _('Guatemala')),
    ('Guinée', _('Guinée')),
    ('Guinée équatoriale', _('Guinée équatoriale')),
    ('Guinée-Bissau', _('Guinée-Bissau')),
    ('Guyana', _('Guyana')),
    ('Haïti', _('Haïti')),
    ('Honduras', _('Honduras')),
    ('Hongrie', _('Hongrie')),
    ('Inde', _('Inde')),
    ('Indonésie', _('Indonésie')),
    ('Irak', _('Irak')),
    ('Iran', _('Iran')),
    ('Irlande', _('Irlande')),
    ('Islande', _('Islande')),
    ('Israël', _('Israël')),
    ('Italie', _('Italie')),
    ('Jamaïque', _('Jamaïque')),
    ('Japon', _('Japon')),
    ('Jordanie', _('Jordanie')),
    ('Kazakhstan', _('Kazakhstan')),
    ('Kenya', _('Kenya')),
    ('Kirghizistan', _('Kirghizistan')),
    ('Kiribati', _('Kiribati')),
    ('Koweït', _('Koweït')),
    ('Laos', _('Laos')),
    ('Lesotho', _('Lesotho')),
    ('Lettonie', _('Lettonie')),
    ('Liban', _('Liban')),
    ('Liberia', _('Liberia')),
    ('Libye', _('Libye')),
    ('Liechtenstein', _('Liechtenstein')),
    ('Lituanie', _('Lituanie')),
    ('Luxembourg', _('Luxembourg')),
    ('Macédoine du Nord', _('Macédoine du Nord')),
    ('Madagascar', _('Madagascar')),
    ('Malaisie', _('Malaisie')),
    ('Malawi', _('Malawi')),
    ('Maldives', _('Maldives')),
    ('Mali', _('Mali')),
    ('Malte', _('Malte')),
    ('Maroc', _('Maroc')),
    ('Marshall', _('Marshall')),
    ('Maurice', _('Maurice')),
    ('Mauritanie', _('Mauritanie')),
    ('Mexique', _('Mexique')),
    ('Micronésie', _('Micronésie')),
    ('Moldavie', _('Moldavie')),
    ('Monaco', _('Monaco')),
    ('Mongolie', _('Mongolie')),
    ('Monténégro', _('Monténégro')),
    ('Mozambique', _('Mozambique')),
    ('Namibie', _('Namibie')),
    ('Nauru', _('Nauru')),
    ('Népal', _('Népal')),
    ('Nicaragua', _('Nicaragua')),
    ('Niger', _('Niger')),
    ('Nigeria', _('Nigeria')),
    ('Norvège', _('Norvège')),
    ('Nouvelle-Zélande', _('Nouvelle-Zélande')),
    ('Oman', _('Oman')),
    ('Ouganda', _('Ouganda')),
    ('Ouzbékistan', _('Ouzbékistan')),
    ('Pakistan', _('Pakistan')),
    ('Palaos', _('Palaos')),
    ('Palestine', _('Palestine')),
    ('Panama', _('Panama')),
    ('Papouasie-Nouvelle-Guinée', _('Papouasie-Nouvelle-Guinée')),
    ('Paraguay', _('Paraguay')),
    ('Pays-Bas', _('Pays-Bas')),
    ('Pérou', _('Pérou')),
    ('Philippines', _('Philippines')),
    ('Pologne', _('Pologne')),
    ('Portugal', _('Portugal')),
    ('Qatar', _('Qatar')),
    ('Roumanie', _('Roumanie')),
    ('Royaume-Uni', _('Royaume-Uni')),
    ('Russie', _('Russie')),
    ('Rwanda', _('Rwanda')),
    ('Saint-Christophe-et-Niévès', _('Saint-Christophe-et-Niévès')),
    ('Saint-Marin', _('Saint-Marin')),
    ('Saint-Vincent-et-les-Grenadines', _('Saint-Vincent-et-les-Grenadines')),
    ('Sainte-Lucie', _('Sainte-Lucie')),
    ('Salomon', _('Salomon')),
    ('Salvador', _('Salvador')),
    ('Samoa', _('Samoa')),
    ('Sao Tomé-et-Principe', _('Sao Tomé-et-Principe')),
    ('Sénégal', _('Sénégal')),
    ('Serbie', _('Serbie')),
    ('Seychelles', _('Seychelles')),
    ('Sierra Leone', _('Sierra Leone')),
    ('Singapour', _('Singapour')),
    ('Slovaquie', _('Slovaquie')),
    ('Slovénie', _('Slovénie')),
    ('Somalie', _('Somalie')),
    ('Soudan', _('Soudan')),
    ('Soudan du Sud', _('Soudan du Sud')),
    ('Sri Lanka', _('Sri Lanka')),
    ('Suède', _('Suède')),
    ('Suisse', _('Suisse')),
    ('Suriname', _('Suriname')),
    ('Syrie', _('Syrie')),
    ('Tadjikistan', _('Tadjikistan')),
    ('Tanzanie', _('Tanzanie')),
    ('Tchad', _('Tchad')),
    ('Tchéquie', _('Tchéquie')),
    ('Thaïlande', _('Thaïlande')),
    ('Timor oriental', _('Timor oriental')),
    ('Togo', _('Togo')),
    ('Tonga', _('Tonga')),
    ('Trinité-et-Tobago', _('Trinité-et-Tobago')),
    ('Tunisie', _('Tunisie')),
    ('Turkménistan', _('Turkménistan')),
    ('Turquie', _('Turquie')),
    ('Tuvalu', _('Tuvalu')),
    ('Ukraine', _('Ukraine')),
    ('Uruguay', _('Uruguay')),
    ('Vanuatu', _('Vanuatu')),
    ('Vatican', _('Vatican')),
    ('Venezuela', _('Venezuela')),
    ('Vietnam', _('Vietnam')),
    ('Yémen', _('Yémen')),
    ('Zambie', _('Zambie')),
    ('Zimbabwe', _('Zimbabwe')),
]
