# Generated by Django 5.2.12 on 2026-03-18 03:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('accounts', '0003_remove_user_two_factor_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('useful_life_years', models.IntegerField(default=5)),
                ('depreciation_method', models.CharField(choices=[('linear', 'Linéaire'), ('declining', 'Dégressif'), ('units', 'Unités de production')], default='linear', max_length=20)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('accumulated_depreciation_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_accum_depreciation', to='accounting.account')),
                ('asset_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_asset', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='accounts.company')),
                ('depreciation_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_depreciation', to='accounting.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('accounting_standard', models.CharField(choices=[('ifrs', 'IFRS'), ('ohada', 'OHADA'), ('syscohada', 'SYSCOHADA')], default='ifrs', max_length=20)),
                ('consolidated_data', models.JSONField(blank=True, default=dict)),
                ('eliminations_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('consolidated_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('consolidated_net_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('consolidated_total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('in_review', 'En revue'), ('approved', 'Approuvé'), ('published', 'Publié')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_consolidations', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidation_reports', to='accounts.company')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('included_entities', models.ManyToManyField(blank=True, related_name='consolidation_reports', to='accounts.entity')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('residual_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('useful_life_years', models.IntegerField(default=5)),
                ('depreciation_method', models.CharField(choices=[('linear', 'Linéaire'), ('declining', 'Dégressif'), ('units', 'Unités de production')], default='linear', max_length=20)),
                ('depreciation_start_date', models.DateField()),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_book_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('disposal_gain_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('active', 'En service'), ('idle', 'Non utilisé'), ('under_repair', 'En réparation'), ('disposed', 'Cédé'), ('fully_depreciated', 'Totalement amorti')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='accounting.assetcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='accounts.company')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='accounts.entity')),
                ('linked_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.transaction')),
            ],
            options={
                'ordering': ['asset_code'],
            },
        ),
        migrations.CreateModel(
            name='InterCompanyElimination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('elimination_type', models.CharField(choices=[('receivable_payable', 'Créances / Dettes intra-groupe'), ('revenue_expense', 'Produits / Charges intra-groupe'), ('investment', 'Titres de participation'), ('dividend', 'Dividendes intra-groupe'), ('unrealized_profit', 'Bénéfices non réalisés')], max_length=30)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminations', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elimination_credit', to='accounting.account')),
                ('debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elimination_debit', to='accounting.account')),
                ('entity_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminations_source', to='accounts.entity')),
                ('entity_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminations_target', to='accounts.entity')),
                ('linked_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.transaction')),
            ],
            options={
                'ordering': ['-period_end', 'elimination_type'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('accumulated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_book_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.transaction')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciations', to='accounting.fixedasset')),
            ],
            options={
                'ordering': ['period'],
                'unique_together': {('asset', 'period')},
            },
        ),
    ]
