# Generated by Django 5.2.12 on 2026-04-14 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_account_templates_from_existing_accounts(apps, schema_editor):
    Account = apps.get_model('accounting', 'Account')
    AccountTemplate = apps.get_model('accounting', 'AccountTemplate')
    Company = apps.get_model('accounts', 'Company')
    db_alias = schema_editor.connection.alias

    candidate_accounts = list(
        Account.objects.using(db_alias)
        .filter(is_system=True)
        .order_by('code', 'created_at')
        .values(
            'code',
            'name',
            'name_en',
            'account_class',
            'account_type',
            'level',
            'is_active',
            'is_system',
            'description',
            'company__accounting_standard',
            'parent__code',
        )
    )
    if not candidate_accounts:
        candidate_accounts = list(
            Account.objects.using(db_alias)
            .order_by('code', 'created_at')
            .values(
                'code',
                'name',
                'name_en',
                'account_class',
                'account_type',
                'level',
                'is_active',
                'is_system',
                'description',
                'company__accounting_standard',
                'parent__code',
            )
        )

    template_defaults_by_key = {}

    for account in candidate_accounts:
        standard = account['company__accounting_standard'] or 'syscohada'
        key = (standard, account['code'])
        if key in template_defaults_by_key:
            continue

        template_defaults_by_key[key] = dict(
            accounting_standard=standard,
            code=account['code'],
            name=account['name'],
            name_en=account['name_en'],
            account_class=account['account_class'],
            account_type=account['account_type'],
            level=account['level'],
            is_active=account['is_active'],
            is_system=account['is_system'],
            description=account['description'],
            parent_code=account['parent__code'],
        )

    AccountTemplate.objects.using(db_alias).bulk_create(
        [
            AccountTemplate(
                accounting_standard=values['accounting_standard'],
                code=values['code'],
                name=values['name'],
                name_en=values['name_en'],
                account_class=values['account_class'],
                account_type=values['account_type'],
                level=values['level'],
                is_active=values['is_active'],
                is_system=values['is_system'],
                description=values['description'],
            )
            for values in template_defaults_by_key.values()
        ],
        batch_size=1000,
        ignore_conflicts=True,
    )

    template_by_key = {
        (template.accounting_standard, template.code): template
        for template in AccountTemplate.objects.using(db_alias).all().only('id', 'accounting_standard', 'code', 'parent_id')
    }

    templates_to_update = []
    for key, template in template_by_key.items():
        parent_code = template_defaults_by_key.get(key, {}).get('parent_code')
        if not parent_code:
            continue
        parent_template = template_by_key.get((key[0], parent_code))
        if parent_template and template.parent_id != parent_template.id:
            template.parent_id = parent_template.id
            templates_to_update.append(template)

    if templates_to_update:
        AccountTemplate.objects.using(db_alias).bulk_update(templates_to_update, ['parent'], batch_size=1000)

    account_table = schema_editor.quote_name(Account._meta.db_table)
    template_table = schema_editor.quote_name(AccountTemplate._meta.db_table)
    company_table = schema_editor.quote_name(Company._meta.db_table)
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"""
            UPDATE {account_table} AS account
            SET template_id = template.id
            FROM {company_table} AS company, {template_table} AS template
            WHERE account.company_id = company.id
              AND template.accounting_standard = company.accounting_standard
              AND template.code = account.code
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_assetcategory_consolidationreport_fixedasset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accounting_standard', models.CharField(choices=[('syscohada', 'SYSCOHADA Révisé'), ('ohada', 'OHADA'), ('ifrs', 'IFRS Complets'), ('ifrs_pme', 'IFRS PME'), ('pcge_maroc', 'PCGE Maroc'), ('syscoa', 'SYSCOA UEMOA')], default='syscohada', max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('account_class', models.CharField(choices=[('1', 'Comptes de ressources durables'), ('2', "Comptes d'actif immobilisé"), ('3', 'Comptes de stocks'), ('4', 'Comptes de tiers'), ('5', 'Comptes de trésorerie'), ('6', 'Comptes de charges'), ('7', 'Comptes de produits'), ('8', 'Comptes de résultat')], max_length=1)),
                ('account_type', models.CharField(choices=[('asset', 'Actif'), ('liability', 'Passif'), ('equity', 'Capitaux propres'), ('income', 'Produits'), ('expense', 'Charges')], max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.accounttemplate')),
            ],
            options={
                'ordering': ['accounting_standard', 'code'],
                'unique_together': {('accounting_standard', 'code')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_accounts', to='accounting.accounttemplate'),
        ),
        migrations.RunPython(seed_account_templates_from_existing_accounts, migrations.RunPython.noop),
    ]
