# Generated by Django 5.2.12 on 2026-03-17 22:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='company name')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='legal name')),
                ('company_type', models.CharField(choices=[('startup', 'Startup'), ('pme', 'PME'), ('eti', 'ETI'), ('enterprise', 'Grande Entreprise'), ('groupe', 'Groupe / Holding')], default='startup', max_length=20)),
                ('accounting_standard', models.CharField(choices=[('syscohada', 'SYSCOHADA Révisé'), ('ohada', 'OHADA'), ('ifrs', 'IFRS Complets'), ('ifrs_pme', 'IFRS PME'), ('pcge_maroc', 'PCGE Maroc'), ('syscoa', 'SYSCOA UEMOA')], default='syscohada', max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('trade_register', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Sénégal', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('legal_form', models.CharField(blank=True, max_length=100)),
                ('capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fiscal_year_start', models.DateField(blank=True, null=True)),
                ('fiscal_year_end', models.DateField(blank=True, null=True)),
                ('base_currency', models.CharField(default='XOF', max_length=3)),
                ('timezone', models.CharField(default='Africa/Dakar', max_length=50)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('is_parent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_plan', models.CharField(choices=[('free', 'Gratuit'), ('startup', 'Startup'), ('pme', 'PME'), ('enterprise', 'Enterprise'), ('groupe', 'Groupe')], default='free', max_length=20)),
                ('subscription_status', models.CharField(choices=[('active', 'Actif'), ('trial', 'Essai'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='trial', max_length=20)),
                ('trial_ends', models.DateTimeField(blank=True, null=True)),
                ('max_users', models.IntegerField(default=1)),
                ('max_entities', models.IntegerField(default=1)),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='accounts.company')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('entity_type', models.CharField(choices=[('hq', 'Siège Social'), ('branch', 'Succursale'), ('subsidiary', 'Filiale'), ('jv', 'Joint-Venture'), ('partnership', 'Partenariat')], default='branch', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Sénégal', max_length=100)),
                ('local_currency', models.CharField(default='XOF', max_length=3)),
                ('accounting_standard', models.CharField(choices=[('syscohada', 'SYSCOHADA Révisé'), ('ohada', 'OHADA'), ('ifrs', 'IFRS Complets'), ('ifrs_pme', 'IFRS PME'), ('pcge_maroc', 'PCGE Maroc'), ('syscoa', 'SYSCOA UEMOA')], default='syscohada', max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='accounts.company')),
            ],
            options={
                'verbose_name': 'entity',
                'verbose_name_plural': 'entities',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('user_type', models.CharField(choices=[('startup', 'Startup'), ('pme', 'PME'), ('eti', 'ETI'), ('enterprise', 'Grande Entreprise'), ('groupe', 'Groupe / Holding')], default='startup', max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('ceo', 'CEO / DG'), ('cfo', 'DAF / CFO'), ('accountant', 'Comptable'), ('treasurer', 'Trésorier'), ('controller', 'Contrôleur de Gestion'), ('hr', 'RH / Paie'), ('procurement', 'Achats'), ('viewer', 'Lecteur')], default='admin', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('timezone', models.CharField(default='Africa/Dakar', max_length=50)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('subscription_plan', models.CharField(choices=[('free', 'Gratuit'), ('startup', 'Startup'), ('pme', 'PME'), ('enterprise', 'Enterprise'), ('groupe', 'Groupe')], default='free', max_length=20)),
                ('subscription_expires', models.DateTimeField(blank=True, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.company')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.entity')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('alert', 'Alerte')], default='info', max_length=20)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('link', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('export', 'Export'), ('import', 'Import')], max_length=20)),
                ('description', models.TextField()),
                ('module', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user activity',
                'verbose_name_plural': 'user activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
