# Generated by Django 5.2.12 on 2026-03-18 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_base_currency_alter_company_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='two_factor_enabled',
        ),
    ]
