# Generated by Django 5.2.12 on 2026-03-18 03:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_assetcategory_consolidationreport_fixedasset_and_more'),
        ('accounts', '0003_remove_user_two_factor_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('cash_forecast', 'Prévision de trésorerie'), ('revenue_forecast', 'Prévision de revenus'), ('expense_anomaly', 'Anomalie de dépenses'), ('fraud_detection', 'Détection de fraude'), ('credit_risk', 'Risque de crédit'), ('profitability', 'Analyse de rentabilité'), ('budget_variance', 'Écart budgétaire'), ('general', 'Analyse générale')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('insights', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='accounts.company')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('warning', 'Avertissement'), ('opportunity', 'Opportunité'), ('risk', 'Risque'), ('info', 'Information'), ('recommendation', 'Recommandation')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_required', models.TextField(blank=True)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('impact_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insights', to='ai_engine.aianalysis')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(choices=[('unusual_amount', 'Montant inhabituel'), ('duplicate', 'Doublon potentiel'), ('unauthorized', 'Transaction non autorisée'), ('timing', 'Anomalie temporelle'), ('pattern', 'Motif inhabituel')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('anomaly_score', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='accounts.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_anomalies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashFlowForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_date', models.DateField()),
                ('horizon', models.CharField(choices=[('3m', '3 mois'), ('6m', '6 mois'), ('12m', '12 mois'), ('18m', '18 mois')], default='12m', max_length=5)),
                ('forecast_data', models.JSONField(default=list)),
                ('min_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_monthly_inflow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_monthly_outflow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('has_liquidity_risk', models.BooleanField(default=False)),
                ('risk_period', models.CharField(blank=True, max_length=50)),
                ('risk_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('model_version', models.CharField(default='prophet-1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='ai_engine.aianalysis')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_forecasts', to='accounts.company')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_forecasts', to='accounts.entity')),
            ],
            options={
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentOCR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('invoice', 'Facture'), ('receipt', 'Reçu'), ('bank_statement', 'Relevé bancaire'), ('contract', 'Contrat'), ('payslip', 'Bulletin de paie'), ('other', 'Autre')], default='invoice', max_length=20)),
                ('file', models.FileField(upload_to='ocr/documents/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('raw_text', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('uploaded', 'Téléchargé'), ('processing', 'Traitement en cours'), ('extracted', 'Données extraites'), ('validated', 'Validé'), ('failed', 'Échec')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_documents', to='accounts.company')),
                ('linked_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_documents', to='accounting.invoice')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
