# Generated by Django 5.2.12 on 2026-03-18 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_user_two_factor_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact_description', models.TextField(blank=True)),
                ('probability', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('status', models.CharField(default='En analyse', max_length=50)),
                ('mitigation_plan', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_risks', to='accounts.company')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('authority', models.CharField(blank=True, max_length=255)),
                ('frequency', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('annual', 'Annuel'), ('event', 'Sur événement')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_requirements', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('annually', 'Annuel'), ('ocassional', 'Occasionnel')], default='monthly', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_types', to='accounts.company')),
            ],
            options={
                'verbose_name': 'type de taxe',
                'verbose_name_plural': 'types de taxes',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaxFiling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('deadline', models.DateField()),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to='compliance/declarations/')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'À soumettre'), ('filed', 'Déposée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_filings', to='accounts.company')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_filings', to='accounts.entity')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filings', to='compliance.taxtype')),
            ],
            options={
                'verbose_name': 'déclaration fiscale',
                'verbose_name_plural': 'déclarations fiscales',
                'ordering': ['-deadline'],
            },
        ),
    ]
