# Generated by Django 5.2.12 on 2026-03-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_two_factor_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_account_verified',
        ),
    ]
