# Generated by Django 5.2.12 on 2026-04-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_is_verified_user_is_account_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur société'), ('ceo', 'CEO / DG'), ('cfo', 'DAF / CFO'), ('accountant', 'Comptable'), ('treasurer', 'Trésorier'), ('controller', 'Contrôleur de Gestion'), ('hr', 'RH / Paie'), ('procurement', 'Achats'), ('viewer', 'Lecteur')], default='admin', max_length=20),
        ),
    ]
